# Start from an Ubuntu 20.04 image
FROM ubuntu:20.04

# Set working directory
WORKDIR /app

# Add all .txt files into the container (like requirements.txt)
ADD ./*.txt ./

# Install system dependencies and python3-pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    xvfb \
    scrot \
    x11-utils \
    musl \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install dependencies
RUN cd /app \
    && python3 -m pip install --upgrade pip \
    && pip3 install --no-cache-dir -r requirements.txt \
    && rm -rf /tmp/* && rm -rf /root/.cache/*

# Install Playwright and dependencies
RUN playwright install chrome
# RUN playwright install-deps   # Uncomment if you need additional dependencies for Playwright
